### ISSUE TITLE
csv_editor.py crashes

### ISSUE THREAD

**Issue by jekadwell** [PacktPublishing/Mastering-GUI-Programming-with-Python#9]
The program CSV_editor.py crashes if I try to resize the window or move the scroll bar to view text that is hidden.  I copied and pasted the program from Github.
John Kadwell

**Comment by alandmoore** [comment]
I am unable to reproduce this behavior in Python 3.8 on Linux or Python 3.7 in Windows 10.  Does it happen with any .csv file or a particular one?  Do you get a traceback & exception in your terminal?

**Comment by jekadwell** [comment]
I used Notepad to create the .csv file.  I found out the problem was due to a comma after the last entry on the first row.
I removed the comma and the program no longer crashes when resizing the window.  

However, when I use edit to insert below, and then save the file, a row is inserted after every row.  When I try to open the file the program crashes.

This is what the file looks like in notepad when I created it.

John, Kadwell, Laural, Kadwell
Sue, Kadwell, Sam, Kadwell


This is what the file looks like in notepad after inserting a row below using the editor.

John, Kadwell, Laural, Kadwell

Sue, Kadwell, Sam, Kadwell

Dana,Kadwell,Henry,Kadwell

The csv editor will not open the file when there is a blank row after each row.  The program ends with the following:
Process finished with exit code -1073740791 (0xC0000409)

**Comment by jekadwell** [comment]
I have the same issue using the example csv file.  see below after inserting below and saving.  Note extra rows.

Menu Item, Price, Calories, Fat, Carbohydrates, Protein

Side Salad,3.29,28,0,6,1

Hamburger,2.59,304,12,35,14

French Fries,0.99,376,20,47,2

Fish Sandwich,2.49,403,19,42,16

Chicken nuggets,1.59,278,18,15,14

Cheeseburger,2.79,347,15,37,16

BBQ Sandwich,3.89,504,24,47,25

Fish Taco,1.22,546,23,35,12

**Comment by David-Billingsley** [comment]
I tested the script provided and found no issue, with a test CSV file when reading.  I also tested the file with the data provided above (after removing the spaces ) with no issue when reading the CSV file.  After testing the insert and save function I notice the file will no longer open.  I looked at the file, and noticed that there are blank lines again. Deciding to investigate the save / writing features of the script, I have found the issue. The issue is found in the save_data function,  if you add newline='' your issue will disappear after saving using the script.  I can create a pull request and add the correct line to the file.   If you have any questions please let me know.

**Comment by alandmoore** [comment]
@David-Billingsley That would be great; if you do make a PR, though, please make sure you leave the buggy code as a comment, with a note that this was corrected after publication.  That way readers don't get confused when the online code doesn't match the book.

**Comment by David-Billingsley** [comment]
PR submitted.
